/*

 LINK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define link_frontBank 0
/* CGBpalette entries. */
extern unsigned char link_frontCGB[];
/* Start of tile array. */
extern unsigned char link_front[];

/* End of LINK.H */
